# Generated by Django 5.2.8 on 2025-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('genres_percent', models.JSONField(default=dict, help_text='Porcentajes de géneros')),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('mood_confidence', models.FloatField(default=0.0)),
                ('raw_tags', models.JSONField(default=list, help_text='Tags detectados')),
                ('raw_scores', models.JSONField(default=list, help_text='Scores de los tags')),
                ('mood_scores', models.JSONField(default=dict, help_text='Scores de estados de ánimo')),
            ],
            options={
                'verbose_name': 'Análisis de Audio',
                'verbose_name_plural': 'Análisis de Audio',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
